name: digital_itikaf
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_accessibility_service: ^1.0.0
  flutter_bloc: ^9.1.1
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  path_provider: ^2.1.5
  device_info_plus: ^12.3.0
  flutter_device_apps: ^0.6.0
  google_fonts: ^8.0.1
  material_symbols_icons: ^4.2906.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.11.1
  build_runner: ^2.11.0

flutter:
  uses-material-design: true
